version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    # Step 1: obtain repo from GitHub
    - checkout
    
    executor: python/default
    steps:
      - run:
          # directory where steps are run
          working_directory: ~/quiz/src
          command: python -m unittest discover test -v 
          name: Test

workflows:
  main:
    jobs:
      - build-and-test