version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

        working_directory: ~/repo
    # steps:
    #   - run echo 
  # build-and-test: 
  #   executor: python/default

  #   working_directory: ~/repo
  #   steps:
  #     - checkout  
  #     - run:
  #         command: python -m unittest discover test -v 
  #         name: Test

# workflows:
#   main:
#     jobs:
#       - build