version: 2.1
parameters:
  workingdir:
    type: string
    default: "~/repo"

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test: 
    executor: python/default
    
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - checkout
      - run: echo "$(pwd)" 

      # - run:
      #   command: python -m unittest discover test -v 
      #   name: Testes Unitários

workflows:
  main:
    jobs:
      - build-and-test